import "./global.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-white pt-20">
        <header className="w-screen h-20 bg-red-600 text-center text-3xl fixed top-0 left-0 " > Navbar</header>
        {children}

        <footer className="w-screen h-20 text-3xl bg-zinc-700 fixed bottom-0 left-0">
          <h1 >
            Footer
          </h1>
        </footer>
      </body>
    </html>
  )
}
