
import Link from "next/link"
import "./global.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#2b2d42] text-[#1a68ef] pt-20">
        <header className="w-screen h-20 bg-[] text-center text-3xl fixed top-0 left-0 flex gap-5 justify-center" >
          <Link href='/'>Home</Link>
          <Link href="/about">About</Link>
          <Link href="/products">Product</Link>
          <Link href="/blog">Blog</Link>
          <Link href="/contactUs">Contact Us</Link>
          <Link href="/login">Login</Link>
          <Link href="/registration">Registration</Link></header>
        {children}

        <footer className="w-screen h-20 text-3xl bg-zinc-700 fixed bottom-0 left-0">
          <h1 >
            Footer
          </h1>
        </footer>
      </body>
    </html>
  )
}
